---
- name: "ceph_common | Deploy cephx keyring"
  ansible.builtin.template:
    src: "cephx_keyring.j2"
    dest: "{{ hostvars[inventory_hostname]['ceph_common_conf_dest'] +
      '/ceph.client.' ~ item['name'] ~ '.keyring' }}"
    force: "yes"
    owner: "root"
    group: "root"
    mode: "0400"
  loop: "{{ vars['ceph_common_keyrings_clients'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['ceph_common_conf_dest'] +
      '/ceph.client.' ~ item['name'] ~ '.keyring' }}"
  when:
    - "item['name'] is defined"
    - "item['name'] != ''"
