---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['ceph_common'] is defined"
    - "hostvars[inventory_hostname]['ceph_common'] != ''"
    - "hostvars[inventory_hostname]['ceph_common'] |
      community.general.json_query(vars['ceph_common_install_package']) is
      defined"
    - "hostvars[inventory_hostname]['ceph_common'] |
      community.general.json_query(vars['ceph_common_install_package']) ==
      'true'"
  vars:
    ceph_common_install_package: "[] | map(&install_package || 'false', @) |
      [0]"
- ansible.builtin.import_tasks:
    file: "deploy_ceph_conf.yml"
  when:
    - "vars['ceph_common_settings'] is defined"
    - "vars['ceph_common_settings'] != []"
    - "vars['ceph_common_settings'] != ''"
- ansible.builtin.import_tasks:
    file: "deploy_ceph_rbdmap.yml"
  when:
    - "vars['ceph_common_rbdmap'] is defined"
    - "vars['ceph_common_rbdmap'] != []"
    - "vars['ceph_common_rbdmap'] != ''"
- ansible.builtin.import_tasks:
    file: "deploy_cephx_keyring_etc.yml"
  when:
    - "vars['ceph_common_keyrings_clients'] is defined"
    - "vars['ceph_common_keyrings_clients'] != []"
- ansible.builtin.import_tasks:
    file: "deploy_cephx_keyring_workdir.yml"
- ansible.builtin.import_tasks:
    file: "deploy_rgw_certificate.yml"
  when:
    - "vars['ceph_common_rgw_certificate_result'] is defined"
    - "vars['ceph_common_rgw_certificate_result']['skipped'] is not defined"
