---
- name: "ceph_common | Install the required packages for RedHat via dnf"
  ansible.builtin.dnf:
    name: "{{ hostvars[inventory_hostname]['ceph_common_package'] }}"
    state: "{{ vars['ceph_common_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: "ceph_common | Install the required packages in Debian derivatives"
  ansible.builtin.apt:
    name: "{{ hostvars[inventory_hostname]['ceph_common_package'] }}"
    state: "{{ vars['ceph_common_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: "ceph_common | Install the required packages in ArchLinux derivatives"
  community.general.pacman:
    name: "{{ hostvars[inventory_hostname]['ceph_common_package'] }}"
    state: "{{ vars['ceph_common_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
