---
- name: "ceph_common | Create Ceph working catalogs for Ceph client apps"
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['ceph_common_workdir_dest'] + '/' +
      cephx['type'] + '/ceph-' ~ cephx['name'] }}"
    state: "directory"
    owner: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    group: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    mode: "0750"
  loop: "{{ vars['ceph_common_keyrings_workdir_apps'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "cephx"
    label: "{{ hostvars[inventory_hostname]['ceph_common_workdir_dest'] + '/' +
      cephx['type'] + '/ceph-' ~ cephx['name'] }}"
  when:
    - "cephx['name'] is defined"
    - "cephx['name'] != ''"
- name: "ceph_common | Deploy cephx keyring for Ceph client apps"
  ansible.builtin.template:
    src: "cephx_keyring.j2"
    dest: "{{ hostvars[inventory_hostname]['ceph_common_workdir_dest'] + '/' +
      cephx['type'] + '/ceph-' ~ cephx['name'] ~ '/keyring' }}"
    force: "yes"
    owner: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    group: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    mode: "0400"
  loop: "{{ vars['ceph_common_keyrings_workdir_apps'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "cephx"
    label: "{{ hostvars[inventory_hostname]['ceph_common_workdir_dest'] + '/' +
      cephx['type'] + '/ceph-' ~ cephx['name'] ~ '/keyring' }}"
  when:
    - "cephx['name'] is defined"
    - "cephx['name'] != ''"
- name: "ceph_common | Deploy cephx bootstrap keyring"
  ansible.builtin.template:
    src: "cephx_keyring.j2"
    dest: "{{ hostvars[inventory_hostname]['ceph_common_workdir_dest'] + '/' +
      cephx['type'] + '/ceph.keyring' }}"
    force: "yes"
    owner: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    group: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    mode: "0600"
  loop: "{{ vars['ceph_common_keyrings_workdir_bootstrap'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "cephx"
    label: "{{ hostvars[inventory_hostname]['ceph_common_workdir_dest'] + '/' +
      cephx['type'] + '/ceph.keyring' }}"
  when:
    - "cephx['name'] is defined"
    - "cephx['name'] != ''"
