---
- name: "ceph_common | Deploy cephx keyring"
  ansible.builtin.template:
    src: "cephx_keyring.j2"
    dest: "{{ hostvars[inventory_hostname]['ceph_common_conf_dest'] +
      '/ceph.client.' ~ cephx['name'] ~ '.keyring' }}"
    force: "yes"
    owner: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    group: "{{ hostvars[inventory_hostname]['ceph_common_user_id'] }}"
    mode: "0400"
  loop: "{{ vars['ceph_common_keyrings_clients'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "cephx"
    label: "{{ hostvars[inventory_hostname]['ceph_common_conf_dest'] +
      '/ceph.client.' ~ cephx['name'] ~ '.keyring' }}"
  when:
    - "cephx['name'] is defined"
    - "cephx['name'] != []"
    - "cephx['name'] != ''"
