---
- name: "ceph_common | Deploy cephx keyring"
  ansible.builtin.template:
    src: "cephx_keyring.j2"
    dest: "{{ hostvars[inventory_hostname]['ceph_common_conf_dest'] +
      '/ceph.client.' ~ cephx['name'] ~ '.keyring' }}"
    force: "yes"
    owner: "root"
    group: "root"
    mode: "0400"
  loop: "{{ vars['ceph_common_keyrings_clients'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "cephx"
    label: "{{ 'Keyring: ' +
      hostvars[inventory_hostname]['ceph_common_conf_dest'] + '/ceph.client.' ~
      cephx['name'] ~ '.keyring' }}"
  when:
    - "cephx['name'] is defined"
    - "cephx['name'] not in ['', [], None]"
