---
- name: "ceph_common | Deploy ceph-mgr service configuration"
  ansible.builtin.template:
    src: "ceph_mgr_service.j2"
    dest: "{{ vars['ceph_common_systemd_dir'] +
      '/ceph-mgr@.service.d/override.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Daemon reload"
  when:
    - "vars['ceph_common_systemd']['mgr'] is defined"
    - "vars['ceph_common_systemd']['mgr'] not in ['', [], None]"
