---
- name: "ceph_common | Deploy ceph-exporter service configuration"
  ansible.builtin.template:
    src: "ceph_exporter_service.j2"
    dest: "{{ vars['ceph_common_systemd_dir'] +
      '/ceph-exporter.service.d/override.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Daemon reload"
  when:
    - "vars['ceph_common_systemd']['exporter_hotfix'] is defined"
    - "vars['ceph_common_systemd']['exporter_hotfix'] == 'true'"
